'use client'
import {useState} from 'react'
import type {ReactNode} from 'react'
const API=process.env.NEXT_PUBLIC_API_BASE||'https://trustscan-api-q2s4.onrender.com'
type Scan={scan_id:string,status:string}
const types=[['Android APK','Static analysis','available'],['URL','Web threat analysis','soon'],['Windows EXE','File analysis','soon'],['PDF','Document analysis','soon'],['Office files','Document analysis','soon'],['Archives','Archive analysis','soon']]
async function fetchWithTimeout(url:string,init?:RequestInit,ms=120000){const c=new AbortController();const t=setTimeout(()=>c.abort(),ms);try{return await fetch(url,{...init,signal:c.signal})}finally{clearTimeout(t)}}
export default function Home(){
 const [file,setFile]=useState<File|null>(null),[scan,setScan]=useState<Scan|null>(null),[report,setReport]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 async function analyze(){if(!file)return;setError('');setBusy(true);setReport(null);setScan(null);try{const fd=new FormData();fd.append('file',file);const r=await fetchWithTimeout(`${API}/api/v1/scans`,{method:'POST',body:fd});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.detail||`Upload failed (${r.status})`);setScan(d);let status=d.status;while(!['COMPLETED','FAILED','CANCELLED'].includes(status)){await new Promise(x=>setTimeout(x,1000));const sr=await fetchWithTimeout(`${API}/api/v1/scans/${d.scan_id}`,undefined,30000);const s=await sr.json();if(!sr.ok)throw Error(s.detail||'Could not read scan status');status=s.status;setScan(s)}if(status==='FAILED')throw Error('We could not analyze this APK.');const rr=await fetchWithTimeout(`${API}/api/v1/scans/${d.scan_id}/report`,undefined,30000),rep=await rr.json();if(!rr.ok)throw Error(rep.detail||'Could not load the report');setReport(rep)}catch(e:any){setError(e.name==='AbortError'?'The upload or analysis timed out. Please try again.':e.message||'Something went wrong.')}finally{setBusy(false)}}
 return <main><header><div className="brand"><span className="mark">✓</span> TrustScan</div><nav><a href="#how">How it works</a><a href="#privacy">Privacy</a></nav></header>
 <section className="hero"><div className="heroCopy"><div className="eyebrow">SECURITY, EXPLAINED SIMPLY</div><h1>Know before<br/><em>you open.</em></h1><p>Analyze an app and understand what it can access, what static risks were found, and what deserves your attention.</p><div className="typeGrid">{types.map(([name,desc,state])=><div className={`typeCard ${state}`} key={name}><div className="typeIcon">{name==='Android APK'?'◆':name==='URL'?'↗':name==='Windows EXE'?'▣':name==='PDF'?'▤':name==='Office files'?'▦':'▱'}</div><div><b>{name}</b><span>{desc}</span></div><small>{state==='available'?'Available':'Coming soon'}</small></div>)}</div><div className="uploadPanel"><div className="panelTop"><div><b>Analyze Android APK</b><span>Static analysis only · Max 50 MB</span></div><span className="online">● Engine online</span></div><div className="actions"><label className="upload">{file?file.name:'Choose APK'}<input type="file" accept=".apk,application/vnd.android.package-archive" onChange={e=>{const f=e.target.files?.[0]||null;setFile(f);setError('');if(f&&f.size>50*1024*1024){setError('APK must be 50 MB or smaller.');setFile(null)}}}/></label><button disabled={!file||busy} onClick={analyze}>{busy?'Analyzing…':'Analyze APK'}</button></div><small>Your file is treated as untrusted and is never executed by the API server.</small></div><div className="shield"><div className="shieldicon">✓</div><div className="shieldText"><b>Evidence first</b><p>Facts are separated from interpretation. Unknown stays unknown.</p><span>No malware verdicts from permissions alone.</span></div></div></div></section>
 {error&&<div className="error">{error}</div>}{scan&&<section className="status"><b>{scan.status}</b><span>Real scan state — no fake progress.</span></section>}
 {report&&<section className="report"><div className="reporttop"><div><div className="eyebrow">ANALYSIS REPORT</div><h2>{report.file.application_name||'Unknown application'}</h2><p>{report.file.package_name||'Package unknown'}</p></div><div className="score"><strong>{report.risk.score}</strong><span>/100</span><b>{report.risk.level}</b></div></div><div className="summary"><b>Quick summary</b><p>{report.risk.summary}</p></div><div className="grid"><Card title="What this app requests"><ul>{report.permissions?.length?report.permissions.map((p:any)=><li key={p.permission}><b>{p.name}</b><span>{p.explanation}</span></li>):<li>No requested permissions were extracted.</li>}</ul></Card><Card title="What we found">{report.findings?.length?report.findings.map((f:any)=><div className="finding" key={f.title}><b>{f.title}</b><p>{f.detail}</p></div>):<p>No suspicious static indicators were identified by the current rules.</p>}</Card><Card title="Unknown"><ul>{(report.unknown||[]).map((x:string)=><li key={x}>{x}</li>)}</ul></Card></div><details><summary>Technical details</summary><pre>{JSON.stringify(report.file,null,2)}</pre></details><div className="recommend"><b>Recommendation</b><p>{report.recommendation}</p></div></section>}
 <section id="how" className="how"><div><div className="eyebrow">THE TRUSTSCAN PROMISE</div><h2>Security findings,<br/>without the fear.</h2></div><div><p>TrustScan does not turn a permission into a malware verdict. Static analysis tells us what is declared or embedded in the APK; it cannot prove what happens at runtime.</p><p>URLs, dynamic sandboxing and other file types are shown as future capabilities only.</p></div></section><footer id="privacy">TrustScan MVP · Static APK analysis · No guarantee of safety · Evidence can be incomplete</footer></main>}
function Card({title,children}:{title:string,children:ReactNode}){return <div className="card"><h3>{title}</h3>{children}</div>}
